name: weeek_api
description: sdk to work with WEEEK
version: 0.0.1
homepage: "https://github.com/ingego?tab=repositories"

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  dio: ^5.1.1
  logger: ^1.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
